--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '5836476596633826198438883'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: small-plastic-car
  name: Small Plastic Car
  sku: small-plastic-car
  description: Quibusdam sapiente in tempore quia illo quia eum cum.
  price: 2053.0
  cost_price: 262.6361334100865
  available_on: 2014-06-06 10:58:17.713724000 -05:00
  permalink: small-plastic-car
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Small Plastic Car
    position: 1
    title: Small Plastic Car
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: small-plastic-car-Super-Special-Edition
    price: 2058.0
    cost_price: 2058.0
    quantity: '8861452820069343148008735'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Small Plastic Car Super
        Special Edition
      position: 1
      title: Small Plastic Car Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
