--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: 0222482878108589773234208
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: fantastic-concrete-car
  name: Fantastic Concrete Car
  sku: fantastic-concrete-car
  description: Ut soluta modi quia ipsa delectus qui et.
  price: 5092
  cost_price: 1967
  available_on: 2014-07-07 15:23:46.346199000 -05:00
  permalink: fantastic-concrete-car
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Fantastic Concrete Car
    position: 1
    title: Fantastic Concrete Car
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: fantastic-concrete-car-Super-Special-Edition
    price: 5097
    cost_price: 5097
    quantity: 0442594087749690990397161
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Fantastic Concrete Car Super
        Special Edition
      position: 1
      title: Fantastic Concrete Car Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
