--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '9406938984834131649448714'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: intelligent-granite-computer
  name: Intelligent Granite Computer
  sku: intelligent-granite-computer
  description: Est suscipit rem sapiente illum enim cumque vel.
  price: 6327.0
  cost_price: 4551.357680835489
  available_on: 2014-06-08 19:00:04.888924000 -05:00
  permalink: intelligent-granite-computer
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Granite Computer
    position: 1
    title: Intelligent Granite Computer
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: intelligent-granite-computer-Super-Special-Edition
    price: 6332.0
    cost_price: 6332.0
    quantity: '3510082303940909075414858'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Granite Computer
        Super Special Edition
      position: 1
      title: Intelligent Granite Computer Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
