--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '2173531745263140391509641'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: rustic-steel-table
  name: Rustic Steel Table
  sku: rustic-steel-table
  description: Provident eos dolorum exercitationem.
  price: 2249
  cost_price: 983
  available_on: 2014-06-16 13:34:12.293103000 -05:00
  permalink: rustic-steel-table
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Rustic Steel Table
    position: 1
    title: Rustic Steel Table
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: rustic-steel-table-Super-Special-Edition
    price: 2254
    cost_price: 2254
    quantity: '3809428870183624515374760'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Rustic Steel Table Super
        Special Edition
      position: 1
      title: Rustic Steel Table Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
