--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '5354056509517452682739031'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: intelligent-plastic-shirt
  name: Intelligent Plastic Shirt
  sku: intelligent-plastic-shirt
  description: Ipsa rem ea autem dolores vel facere eum.
  price: 1233
  cost_price: 11
  available_on: 2014-06-08 21:01:13.413118000 -05:00
  permalink: intelligent-plastic-shirt
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Plastic Shirt
    position: 1
    title: Intelligent Plastic Shirt
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: intelligent-plastic-shirt-Super-Special-Edition
    price: 1238
    cost_price: 1238
    quantity: '3543701490575562296206390'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Plastic Shirt
        Super Special Edition
      position: 1
      title: Intelligent Plastic Shirt Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
