--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '8629487941963548508563171'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: ergonomic-plastic-computer
  name: Ergonomic Plastic Computer
  sku: ergonomic-plastic-computer
  description: Ut autem quia qui occaecati enim fugit.
  price: 6353
  cost_price: 5941
  available_on: 2014-06-17 19:32:04.485524000 -05:00
  permalink: ergonomic-plastic-computer
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Ergonomic Plastic Computer
    position: 1
    title: Ergonomic Plastic Computer
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: ergonomic-plastic-computer-Super-Special-Edition
    price: 6358
    cost_price: 6358
    quantity: '4805597050265733522551889'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Ergonomic Plastic Computer
        Super Special Edition
      position: 1
      title: Ergonomic Plastic Computer Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
