--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '9769557017503194523276308'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: gorgeous-granite-gloves
  name: Gorgeous Granite Gloves
  sku: gorgeous-granite-gloves
  description: Quis praesentium et numquam quia officia saepe ut.
  price: 3377
  cost_price: 1064
  available_on: 2014-06-12 18:28:43.664467000 -05:00
  permalink: gorgeous-granite-gloves
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Granite Gloves
    position: 1
    title: Gorgeous Granite Gloves
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: gorgeous-granite-gloves-Super-Special-Edition
    price: 3382
    cost_price: 3382
    quantity: 0560325540321228318991149
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Granite Gloves
        Super Special Edition
      position: 1
      title: Gorgeous Granite Gloves Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
