--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '8651235158596955353986827'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: practical-rubber-hat
  name: Practical Rubber Hat
  sku: practical-rubber-hat
  description: Ullam quia nisi nesciunt voluptas rerum.
  price: 4982.0
  cost_price: 1443.4668758236567
  available_on: 2014-06-06 11:08:15.834848000 -05:00
  permalink: practical-rubber-hat
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Practical Rubber Hat
    position: 1
    title: Practical Rubber Hat
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: practical-rubber-hat-Super-Special-Edition
    price: 4987.0
    cost_price: 4987.0
    quantity: '6619197452010855449753965'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Practical Rubber Hat Super
        Special Edition
      position: 1
      title: Practical Rubber Hat Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
