--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '3923211657548142610758661'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: fantastic-steel-pants
  name: Fantastic Steel Pants
  sku: fantastic-steel-pants
  description: In officiis sunt ea.
  price: 7332
  cost_price: 1042
  available_on: 2014-07-08 15:38:04.590548000 -05:00
  permalink: fantastic-steel-pants
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Fantastic Steel Pants
    position: 1
    title: Fantastic Steel Pants
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: fantastic-steel-pants-Super-Special-Edition
    price: 7337
    cost_price: 7337
    quantity: '6916384901899944934565263'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Fantastic Steel Pants Super
        Special Edition
      position: 1
      title: Fantastic Steel Pants Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
