--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '7329751436364986631609216'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: intelligent-concrete-gloves
  name: Intelligent Concrete Gloves
  sku: intelligent-concrete-gloves
  description: Excepturi consectetur dignissimos eos ipsam.
  price: 2828
  cost_price: 1823
  available_on: 2014-06-16 14:33:14.219914000 -05:00
  permalink: intelligent-concrete-gloves
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Concrete Gloves
    position: 1
    title: Intelligent Concrete Gloves
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: intelligent-concrete-gloves-Super-Special-Edition
    price: 2833
    cost_price: 2833
    quantity: '7374617854689244147455054'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Intelligent Concrete Gloves
        Super Special Edition
      position: 1
      title: Intelligent Concrete Gloves Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
