--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '7938959660752921736974103'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: gorgeous-plastic-car
  name: Gorgeous Plastic Car
  sku: gorgeous-plastic-car
  description: Voluptatem et quas amet nobis nostrum.
  price: 88
  cost_price: 87
  available_on: 2014-07-08 15:58:09.230369000 -05:00
  permalink: gorgeous-plastic-car
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Plastic Car
    position: 1
    title: Gorgeous Plastic Car
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: gorgeous-plastic-car-Super-Special-Edition
    price: 93
    cost_price: 93
    quantity: '4077059607797785085045727'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Plastic Car Super
        Special Edition
      position: 1
      title: Gorgeous Plastic Car Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
