--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: 0486851204716927752305862
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: practical-wooden-car
  name: Practical Wooden Car
  sku: practical-wooden-car
  description: Porro nulla sapiente neque molestiae ab quaerat sunt vel.
  price: 1759
  cost_price: 114
  available_on: 2014-06-12 11:18:54.416088000 -05:00
  permalink: practical-wooden-car
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Practical Wooden Car
    position: 1
    title: Practical Wooden Car
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: practical-wooden-car-Super-Special-Edition
    price: 1764
    cost_price: 1764
    quantity: '4221088520355849350791301'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Practical Wooden Car Super
        Special Edition
      position: 1
      title: Practical Wooden Car Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
