--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '9153226902767234582752599'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: small-steel-shoes
  name: Small Steel Shoes
  sku: small-steel-shoes
  description: Suscipit saepe qui repellendus.
  price: 8334
  cost_price: 6103
  available_on: 2014-07-08 10:16:50.446487000 -05:00
  permalink: small-steel-shoes
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Small Steel Shoes
    position: 1
    title: Small Steel Shoes
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: small-steel-shoes-Super-Special-Edition
    price: 8339
    cost_price: 8339
    quantity: '3398195160548292712986737'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Small Steel Shoes Super
        Special Edition
      position: 1
      title: Small Steel Shoes Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
