--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '8810617736576713665077985'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: awesome-plastic-computer
  name: Awesome Plastic Computer
  sku: awesome-plastic-computer
  description: Non praesentium amet cum nihil est dicta.
  price: 4858.0
  cost_price: 25.455084375495048
  available_on: 2014-06-06 11:36:25.164425000 -05:00
  permalink: awesome-plastic-computer
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Awesome Plastic Computer
    position: 1
    title: Awesome Plastic Computer
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: awesome-plastic-computer-Super-Special-Edition
    price: 4863.0
    cost_price: 4863.0
    quantity: '9794683465428161396807466'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Awesome Plastic Computer
        Super Special Edition
      position: 1
      title: Awesome Plastic Computer Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
