--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
request_id: '7420037958183242607051891'
product: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: gorgeous-concrete-chair
  name: Gorgeous Concrete Chair
  sku: gorgeous-concrete-chair
  description: Voluptate reiciendis debitis alias.
  price: 36
  cost_price: 35
  available_on: 2014-07-07 12:21:03.777344000 -05:00
  permalink: gorgeous-concrete-chair
  meta_description: 
  meta_keywords: 
  shipping_category: Default
  taxons:
  - - Categories
    - Clothes
    - T-Shirts
  - - Brands
    - Spree
  - - Brands
    - Open Source
  options:
  - color
  - size
  properties: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    material: cotton
    fit: smart fit
  images:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Concrete Chair
    position: 1
    title: Gorgeous Concrete Chair
    type: thumbnail
    dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      height: 220
      width: 100
  variants:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sku: gorgeous-concrete-chair-Super-Special-Edition
    price: 41
    cost_price: 41
    quantity: '9127529348896007136603503'
    options: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      color: GREY
      size: S
    images:
    - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      url: http://dummyimage.com/600x400/000/fff.jpg&text=Gorgeous Concrete Chair
        Super Special Edition
      position: 1
      title: Gorgeous Concrete Chair Super Special Edition
      type: thumbnail
      dimensions: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        height: 220
        width: 100
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  highrise.api_token: thisIsAFakeKey123
  highrise.site_url: http://www.example.com
